version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - mongo
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    env_file: config/secrets.yml
    command: bundle exec ruby bin/bot.rb
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  mongo:
    image: "mongo:4.4"
    env_file: config/secrets.yml
    ports:
      - "27018:27017"
    volumes:
      - "mongodb:/var/lib/mongodb/data"
  redis:
    image: redis:6.2
    ports:
      - "6379"
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "ping" ]
volumes:
  gem_cache:
  redis:
  mongodb:

