version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    env_file: config/secrets.yml
    command: ruby bin/bot.rb
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  redis:
    image: redis:6.2
    ports:
      - 6379
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "ping" ]
volumes:
  gem_cache:
  redis:

